apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cheikhoul-khadim-niang
  namespace: {{ .Values.namespace }}
  labels:
    app: cheikhoul-khadim-niang
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cheikhoul-khadim-niang
  template:
    metadata:
      labels:
        app: cheikhoul-khadim-niang
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10