apiVersion: v1
kind: Service
metadata:
  name: app-cheikhoul-khadim-niang
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cheikhoul-khadim-niang
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}